feat(rpc): remove bc calls for arianee-api calls
Arianee/arianee-rpc-server pull request #86
Opened 2023-09-05 15:19 UTC by CyrilCartoux

https://www.notion.so/arianee/Update-arianee-APG-804b5c0f41554750a254e78aef124fc7?pvs=4

2023-09-05 15:20 UTC, stefdelec approved these changes

2023-09-06 07:27 UTC, alexishecf requested changes

2023-09-06 07:27 UTC, alexishecf commented on src/helpers/readCertificate.ts
> +  const {issuer, owner, requestKey, viewKey, proofKey} = await arianeeApiClient.network.getNft(tempWallet.configuration.networkName, certificateId) as any;
why do you cast it as any?

2023-09-06 10:43 UTC, stefdelec approved these changes

2023-09-07 07:32 UTC, alexishecf approved these changes

2023-09-07 09:38 UTC, merged